Ground Texture Sim: ground_texture_sim.name_configuration.NameConfigurator Class Reference
ground_texture_sim.name_configuration.NameConfigurator Class Reference
A class to assist with configuring the names of image files, folders, and list files.
Public Member Functions
None __init__ (self, str output_folder, str sequence_type, int sequence_number, int texture_number, str camera_name)
Construct the class with given sequence and texture information.
str create_image_path (self, int index, bool absolute=False)
Assemble the directory and name of a particular image to use for its path.
None meters_txt_file (self)
Return the absolute path of the *_meters.txt file.
None test_file (self)
Return the absolute path of the *.test file.
None txt_file (self)
Return the absolute path of the *.txt file.
Private Attributes
_base_name
The base name of the three top-level files listing images and poses.
_camera_name
The name of the camera in Blender.
_current_date
The current date data is collected.
_output_folder
The absolute path of the folder containing all data.
_sequence_number
A unique number, relative to the date and sequence type, to identify this event.
_sequence_type
A string description of which type of data collection run this is.
_texture_number
An integer representing the texture type mapped.
Detailed Description
A class to assist with configuring the names of image files, folders, and list files.
Definition at line 8 of file name_configuration.py.
Constructor & Destructor Documentation
__init__()
None ground_texture_sim.name_configuration.NameConfigurator.__init__ (self, str output_folder, str sequence_type, int sequence_number, int texture_number, str camera_name)
Construct the class with given sequence and texture information.
Parameters
output_folder The root output folder under which all data resides.
sequence_type A string description of which type of data collection run this is.
sequence_number A unique number, relative to the date and sequence type, to identify this particular data collection event.
texture_number An integer representing the texture type mapped.
camera_name The name of the camera in Blender.
Definition at line 13 of file name_configuration.py.
                 texture_number: int, camera_name: str) -> None:
        """!
        @brief Construct the class with given sequence and texture information.
        @param output_folder The root output folder under which all data resides.
        @param sequence_type A string description of which type of data collection run this is.
        @param sequence_number A unique number, relative to the date and sequence type, to identify
        this particular data collection event.
        @param texture_number An integer representing the texture type mapped.
        @param camera_name The name of the camera in Blender.
        """
        ## The absolute path of the folder containing all data.
        self._output_folder = path.abspath(output_folder)
        ## The current date data is collected
        self._current_date = datetime.date.today()
        ## A string description of which type of data collection run this is.
        self._sequence_type = sequence_type
        ## A unique number, relative to the date and sequence type, to identify this event.
        self._sequence_number = sequence_number
        ## An integer representing the texture type mapped.
        self._texture_number = texture_number
        ## The name of the camera in Blender.
        self._camera_name = camera_name
        ## The base name of the three top-level files listing images and poses.
        self._base_name = F'{self._sequence_type}_{self._current_date.strftime("%y%m%d")}'
References ground_texture_sim.name_configuration.NameConfigurator.__init__().
Referenced by ground_texture_sim.name_configuration.NameConfigurator.__init__().
Member Function Documentation
create_image_path()
str ground_texture_sim.name_configuration.NameConfigurator.create_image_path (self, int index, bool absolute = False)
Assemble the directory and name of a particular image to use for its path.
From the output directory, this will go in:
sequence_type/date_collected/sequence_number/
HDG$VersionNumber_t$TextureNumber_$SequenceType_
$DateOfRecording_s$SequenceNumber_c01_i$ImageNumber.png
Parameters
index The image number to use
absolute True if the returned path should be absolute, false if it should be relative to output.
Returns
A relative path to the image location, relative to the output directory.
Definition at line 39 of file name_configuration.py.
    def create_image_path(self, index: int, absolute: bool = False) -> str:
        """!
        @brief Assemble the directory and name of a particular image to use for its path.
        From the output directory, this will go in:
        ```
        sequence_type/date_collected/sequence_number/
        HDG$VersionNumber_t$TextureNumber_$SequenceType_
        $DateOfRecording_s$SequenceNumber_c01_i$ImageNumber.png
        ```
        @param index The image number to use
        @param absolute True if the returned path should be absolute, false if it should be relative
        to *output*.
        @return A relative path to the image location, relative to the output directory.
        """
        # Create the directory relative to the output folder.
        date_folder = self._current_date.strftime('%y%m%d')
        sequence_number_folder = F'seq{self._sequence_number:04d}'
        file_directory = path.join(
            self._sequence_type, date_folder, sequence_number_folder)
        # Then the filename
        texture_name = F't{self._texture_number:03d}'
        date_name = self._current_date.strftime('%Y-%m-%d')
        sequence_number_name = F's{self._sequence_number:04d}'
        image_name = F'i{index:07d}'
        file_name = F'HDG2_{texture_name}_{self._sequence_type}_{date_name}' \
            F'_{sequence_number_name}_{self._camera_name}_{image_name}.png'
        result = path.join(file_directory, file_name)
        # Make absolute or relative, depending on the specification
        if absolute:
            result = path.join(self._output_folder, result)
        return result
References ground_texture_sim.name_configuration.NameConfigurator._current_date, ground_texture_sim.name_configuration.NameConfigurator._output_folder, ground_texture_sim.name_configuration.NameConfigurator._sequence_type, and ground_texture_sim.name_configuration.NameConfigurator.create_image_path().
Referenced by ground_texture_sim.name_configuration.NameConfigurator.create_image_path().
meters_txt_file()
None ground_texture_sim.name_configuration.NameConfigurator.meters_txt_file (self)
Return the absolute path of the *_meters.txt file.
Returns
The absolute path for that file.
Definition at line 74 of file name_configuration.py.
    def meters_txt_file(self) -> None:
        """!
        @brief Return the absolute path of the *_meters.txt file.
        @return The absolute path for that file.
        """
        return F'{self._base_name}_meters.txt'
References ground_texture_sim.name_configuration.NameConfigurator.meters_txt_file().
Referenced by ground_texture_sim.name_configuration.NameConfigurator.meters_txt_file().
test_file()
None ground_texture_sim.name_configuration.NameConfigurator.test_file (self)
Return the absolute path of the *.test file.
Returns
The absolute path for that file.
Definition at line 82 of file name_configuration.py.
    def test_file(self) -> None:
        """!
        @brief Return the absolute path of the *.test file.
        @return The absolute path for that file.
        """
        return F'{self._base_name}.test'
References ground_texture_sim.name_configuration.NameConfigurator.test_file().
Referenced by ground_texture_sim.name_configuration.NameConfigurator.test_file().
txt_file()
None ground_texture_sim.name_configuration.NameConfigurator.txt_file (self)
Return the absolute path of the *.txt file.
Returns
The absolute path for that file.
Definition at line 90 of file name_configuration.py.
    def txt_file(self) -> None:
        """!
        @brief Return the absolute path of the *.txt file.
        @return The absolute path for that file.
        """
        return F'{self._base_name}.txt'
References ground_texture_sim.name_configuration.NameConfigurator.txt_file().
Referenced by ground_texture_sim.name_configuration.NameConfigurator.txt_file().
Member Data Documentation
_base_name
ground_texture_sim.name_configuration.NameConfigurator._base_name private
The base name of the three top-level files listing images and poses.
Definition at line 37 of file name_configuration.py.
_camera_name
ground_texture_sim.name_configuration.NameConfigurator._camera_name private
The name of the camera in Blender.
Definition at line 35 of file name_configuration.py.
Referenced by ground_texture_sim.blender_interface.BlenderInterface.camera_name().
_current_date
ground_texture_sim.name_configuration.NameConfigurator._current_date private
The current date data is collected.
Definition at line 27 of file name_configuration.py.
Referenced by ground_texture_sim.name_configuration.NameConfigurator.create_image_path().
_output_folder
ground_texture_sim.name_configuration.NameConfigurator._output_folder private
The absolute path of the folder containing all data.
Definition at line 25 of file name_configuration.py.
Referenced by ground_texture_sim.name_configuration.NameConfigurator.create_image_path().
_sequence_number
ground_texture_sim.name_configuration.NameConfigurator._sequence_number private
A unique number, relative to the date and sequence type, to identify this event.
Definition at line 31 of file name_configuration.py.
_sequence_type
ground_texture_sim.name_configuration.NameConfigurator._sequence_type private
A string description of which type of data collection run this is.
Definition at line 29 of file name_configuration.py.
Referenced by ground_texture_sim.name_configuration.NameConfigurator.create_image_path().
_texture_number
ground_texture_sim.name_configuration.NameConfigurator._texture_number private
An integer representing the texture type mapped.
Definition at line 33 of file name_configuration.py.
The documentation for this class was generated from the following file:
ground_texture_sim/name_configuration.py