Ground Texture Sim: ground_texture_sim.tests.test_configuration_loader.TestLoadConfig Class Reference
ground_texture_sim.tests.test_configuration_loader.TestLoadConfig Class Reference
This class tests the load_config function.
Public Member Functions
None test_missing_camera_elements (self)
Test that the camera name must be included in the user provided JSON.
None test_missing_sequence_elements (self)
Test that all required sequence keys are checked for.
None test_missing_top_levels (self)
Test the function raises an Exception if certain required entries are not present.
None test_nonexistent_file (self)
Test the function raises an Exception if the specified file does not exist.
None test_not_json (self)
Test the function raises an Exception if the specified file is not in JSON format.
None test_optional_missing (self)
Test the function includes optional values if not found in the specified file.
None test_sequence_number_is_number (self)
Test the loader verifies the sequence number is an actual number.
None test_successful (self)
Test the function works as expected if the specified file is correct.
None test_texture_number_is_number (self)
Test the loader verifies the sequence number is an actual number.
Private Member Functions
Dict _create_correct_config (self, bool include_options=True)
A helper function to create correctly formatted Dicts, with or without options.
str _dict_to_string (self, Dict input_dict)
A helper function to convert Dicts to correctly formatted JSON strings.
Detailed Description
This class tests the load_config function.
Definition at line 11 of file test_configuration_loader.py.
Member Function Documentation
_create_correct_config()
Dict ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config (self, bool include_options = True) private
A helper function to create correctly formatted Dicts, with or without options.
Parameters
include_options Whether or not to include all optional keys with default values.
Returns
The Dict
Definition at line 16 of file test_configuration_loader.py.
    def _create_correct_config(self, include_options: bool = True) -> Dict:
        """!
        @brief A helper function to create correctly formatted Dicts, with or without options.
        @param include_options Whether or not to include all optional keys with default values.
        @return The Dict
        """
        result = {
            'camera': {
                'name': 'Camera'
            },
            'output': 'output/',
            'sequence': {
                'sequence_number': 1,
                'sequence_type': 'regular',
                'texture_number': 1
            },
            'trajectory': 'trajectory.txt'
        }
        if include_options:
            result['camera']['x'] = 0.0
            result['camera']['y'] = 0.0
            result['camera']['z'] = 0.0
            result['camera']['roll'] = 0.0
            result['camera']['pitch'] = 1.5708
            result['camera']['yaw'] = 0.0
        return result
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_camera_elements(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_sequence_elements(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_top_levels(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_optional_missing(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_sequence_number_is_number(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_successful(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_texture_number_is_number().
_dict_to_string()
str ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string (self, Dict input_dict) private
A helper function to convert Dicts to correctly formatted JSON strings.
Parameters
input_dict The dictionary to format as a JSON string.
Returns
A JSON string
Definition at line 43 of file test_configuration_loader.py.
    def _dict_to_string(self, input_dict: Dict) -> str:
        """!
        @brief A helper function to convert Dicts to correctly formatted JSON strings.
        @param input_dict The dictionary to format as a JSON string.
        @return A JSON string
        """
        return json.dumps(input_dict, indent=4)
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_camera_elements(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_sequence_elements(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_top_levels(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_optional_missing(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_sequence_number_is_number(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_successful(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_texture_number_is_number().
test_missing_camera_elements()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_camera_elements (self)
Test that the camera name must be included in the user provided JSON.
Returns
None
Definition at line 51 of file test_configuration_loader.py.
    def test_missing_camera_elements(self) -> None:
        """!
        @brief Test that the camera name must be included in the user provided JSON.
        @return None
        """
        # Name must be specified
        input_dict = self._create_correct_config(True)
        input_dict['camera'].pop('name')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
        # Camera must also be specified
        input_dict.pop('camera')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_camera_elements().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_camera_elements().
test_missing_sequence_elements()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_sequence_elements (self)
Test that all required sequence keys are checked for.
Returns
None
Definition at line 68 of file test_configuration_loader.py.
    def test_missing_sequence_elements(self) -> None:
        """!
        @brief Test that all required sequence keys are checked for.
        @return None
        """
        # Texture number
        input_dict = self._create_correct_config(True)
        input_dict['sequence'].pop('texture_number')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
        # Sequence type
        input_dict = self._create_correct_config(True)
        input_dict['sequence'].pop('sequence_type')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
        # Sequence number
        input_dict = self._create_correct_config(True)
        input_dict['sequence'].pop('sequence_number')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_sequence_elements().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_sequence_elements().
test_missing_top_levels()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_top_levels (self)
Test the function raises an Exception if certain required entries are not present.
This ensures that 'trajectory' and 'output' are both required.
Returns
None
Definition at line 92 of file test_configuration_loader.py.
    def test_missing_top_levels(self) -> None:
        """!
        @brief Test the function raises an Exception if certain required entries are not present.
        This ensures that 'trajectory' and 'output' are both required.
        @return None
        """
        # Test that trajectory must be there.
        input_dict = self._create_correct_config(True)
        input_dict.pop('trajectory')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
        input_dict = self._create_correct_config(True)
        input_dict.pop('output')
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(KeyError, _load_config, 'config.json',)
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_top_levels().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_missing_top_levels().
test_nonexistent_file()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_nonexistent_file (self)
Test the function raises an Exception if the specified file does not exist.
Normally, we mock the file open. However, in this case, we can just pass a file that doesn't actually exist and expect the error.
Returns
None
Definition at line 112 of file test_configuration_loader.py.
    def test_nonexistent_file(self) -> None:
        """!
        @brief Test the function raises an Exception if the specified file does not exist.
        Normally, we mock the file open. However, in this case, we can just pass a file that doesn't
        actually exist and expect the error.
        @return None
        """
        self.assertRaises(FileNotFoundError, _load_config,
                          'non_a_real_file.json')
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_nonexistent_file().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_nonexistent_file().
test_not_json()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_not_json (self)
Test the function raises an Exception if the specified file is not in JSON format.
Returns
None
Definition at line 124 of file test_configuration_loader.py.
    def test_not_json(self) -> None:
        """!
        @brief Test the function raises an Exception if the specified file is not in JSON format.
        @return None
        """
        input_string = 'not a json\n'
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(json.JSONDecodeError,
                              _load_config, 'config.json')
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_not_json().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_not_json().
test_optional_missing()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_optional_missing (self)
Test the function includes optional values if not found in the specified file.
Returns
None
Definition at line 134 of file test_configuration_loader.py.
    def test_optional_missing(self) -> None:
        """!
        @brief Test the function includes optional values if not found in the specified file.
        @return None
        """
        # Test if no optional values are provided.
        input_dict = self._create_correct_config(False)
        expected_results = self._create_correct_config(True)
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            result = _load_config('config.json')
            self.assertDictEqual(d1=result, d2=expected_results,
                                 msg='Optional values not filled in.')
        # Test if only some options are provided
        input_dict['camera']['x'] = 5.0
        expected_results['camera']['x'] = 5.0
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            result = _load_config('config.json')
            self.assertDictEqual(d1=result, d2=expected_results,
                                 msg='Optional values not filled in.')
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_optional_missing().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_optional_missing().
test_sequence_number_is_number()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_sequence_number_is_number (self)
Test the loader verifies the sequence number is an actual number.
Returns
None
Definition at line 156 of file test_configuration_loader.py.
    def test_sequence_number_is_number(self) -> None:
        """!
        @brief Test the loader verifies the sequence number is an actual number.
        @return None
        """
        input_dict = self._create_correct_config(True)
        # Switch to a string
        input_dict['sequence']['sequence_number'] = "blah"
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(TypeError, _load_config, 'config.json')
        # Floats aren't supported either
        input_dict['sequence']['sequence_number'] = "2.1"
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(TypeError, _load_config, 'config.json')
        # Strings that can convert to ints are fine though
        input_dict['sequence']['sequence_number'] = "2"
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            result = _load_config('config.json')
            self.assertEqual(result['sequence']['sequence_number'], 2)
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_sequence_number_is_number().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_sequence_number_is_number().
test_successful()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_successful (self)
Test the function works as expected if the specified file is correct.
Returns
None
Definition at line 179 of file test_configuration_loader.py.
    def test_successful(self) -> None:
        """!
        @brief Test the function works as expected if the specified file is correct.
        @return None
        """
        input_dict = self._create_correct_config(True)
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            result = _load_config('config.json')
            self.assertDictEqual(d1=result, d2=input_dict,
                                 msg='Unable to read JSON into Dict')
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_successful().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_successful().
test_texture_number_is_number()
None ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_texture_number_is_number (self)
Test the loader verifies the sequence number is an actual number.
Returns
None
Definition at line 191 of file test_configuration_loader.py.
    def test_texture_number_is_number(self) -> None:
        """!
        @brief Test the loader verifies the sequence number is an actual number.
        @return None
        """
        input_dict = self._create_correct_config(True)
        # Switch to a string
        input_dict['sequence']['texture_number'] = "blah"
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(TypeError, _load_config, 'config.json')
        # Floats aren't supported either
        input_dict['sequence']['texture_number'] = "2.1"
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(TypeError, _load_config, 'config.json')
        # Strings that can convert to ints are fine though
        input_dict['sequence']['texture_number'] = "2"
        input_string = self._dict_to_string(input_dict)
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            result = _load_config('config.json')
            self.assertEqual(result['sequence']['texture_number'], 2)
References ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._create_correct_config(), ground_texture_sim.tests.test_configuration_loader.TestLoadConfig._dict_to_string(), and ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_texture_number_is_number().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadConfig.test_texture_number_is_number().
The documentation for this class was generated from the following file:
ground_texture_sim/tests/test_configuration_loader.py