Ground Texture Sim: ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix Class Reference
ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix Class Reference
Test that the create_transform_matrix function works.
Public Member Functions
None test_full_rotation (self)
Test the function works with arbitrary values.
None test_identity (self)
Test that zeros produce the identity transform.
Detailed Description
Test that the create_transform_matrix function works.
Definition at line 9 of file test_transforms.py.
Member Function Documentation
test_full_rotation()
None ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix.test_full_rotation (self)
Test the function works with arbitrary values.
Returns
None
Definition at line 14 of file test_transforms.py.
    def test_full_rotation(self) -> None:
        """!
        @brief Test the function works with arbitrary values.
        @return None
        """
        expected_result = numpy.array([
            [0.0, 0.0, 1.0, 1.0],
            [1.0, 0.0, 0.0, 2.0],
            [0.0, 1.0, 0.0, 3.0],
            [0.0, 0.0, 0.0, 1.0]
        ])
        result = transforms.create_transform_matrix(
            1.0, 2.0, 3.0, numpy.pi, numpy.pi / 2.0, -numpy.pi / 2.0)
        self.assertTrue(numpy.allclose(expected_result, result))
References ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix.test_full_rotation().
Referenced by ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix.test_full_rotation().
test_identity()
None ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix.test_identity (self)
Test that zeros produce the identity transform.
Returns
None
Definition at line 29 of file test_transforms.py.
    def test_identity(self) -> None:
        """!
        @brief Test that zeros produce the identity transform.
        @return None
        """
        expected_result = numpy.identity(4)
        result = transforms.create_transform_matrix(
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
        self.assertTrue(numpy.allclose(expected_result, result))
References ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix.test_identity().
Referenced by ground_texture_sim.tests.test_transforms.TestCreateTransformMatrix.test_identity().
The documentation for this class was generated from the following file:
ground_texture_sim/tests/test_transforms.py