Ground Texture Sim: ground_texture_sim.tests.test_configuration_loader.TestParseArgs Class Reference
ground_texture_sim.tests.test_configuration_loader.TestParseArgs Class Reference
This class tests the parse_args function.
Public Member Functions
None test_help_flag (self)
Test that the system exists if the -h flag is passed.
None test_no_args (self)
Test that the system exists if no JSON file is provided.
None test_too_many_args (self)
Test that the system exists if too many arguments are present.
None test_with_filename (self)
Test that the argument for the JSON is correctly parsed.
Detailed Description
This class tests the parse_args function.
Definition at line 290 of file test_configuration_loader.py.
Member Function Documentation
test_help_flag()
None ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_help_flag (self)
Test that the system exists if the -h flag is passed.
Returns
None
Definition at line 295 of file test_configuration_loader.py.
    def test_help_flag(self) -> None:
        """!
        @brief Test that the system exists if the -h flag is passed.
        @return None
        """
        args = ['blender', '--python',
                'generate_data.py', '-b', '--', '-h']
        self.assertRaises(SystemExit, _parse_args, args)
References ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_help_flag().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_help_flag().
test_no_args()
None ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_no_args (self)
Test that the system exists if no JSON file is provided.
Returns
None
Definition at line 304 of file test_configuration_loader.py.
    def test_no_args(self) -> None:
        """!
        @brief Test that the system exists if no JSON file is provided.
        @return None
        """
        args = ['blender', '--python', 'generate_data.py', '-b']
        self.assertRaises(SystemExit, _parse_args, args)
References ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_no_args().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_no_args().
test_too_many_args()
None ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_too_many_args (self)
Test that the system exists if too many arguments are present.
Returns
None
Definition at line 312 of file test_configuration_loader.py.
    def test_too_many_args(self) -> None:
        """!
        @brief Test that the system exists if too many arguments are present.
        @return None
        """
        args = ['blender', '--python', 'generate_data.py',
                '-b', '--', 'config.json', 'other_config.json']
        self.assertRaises(SystemExit, _parse_args, args)
References ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_too_many_args().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_too_many_args().
test_with_filename()
None ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_with_filename (self)
Test that the argument for the JSON is correctly parsed.
Returns
None
Definition at line 321 of file test_configuration_loader.py.
    def test_with_filename(self) -> None:
        """!
        @brief Test that the argument for the JSON is correctly parsed.
        @return None
        """
        args = ['blender', '--python',
                'generate_data.py', '-b', '--', 'config.json']
        result = _parse_args(args)
        self.assertEqual(result, 'config.json',
                         msg='Unable to successfully extract JSON file.')
References ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_with_filename().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestParseArgs.test_with_filename().
The documentation for this class was generated from the following file:
ground_texture_sim/tests/test_configuration_loader.py