Ground Texture Sim: ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory Class Reference
ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory Class Reference
This class tests the read_poses function.
Public Member Functions
None test_empty_file (self)
This method verifies that the function returns an empty list if the file is empty.
None test_nonexistent_file (self)
This method verifies that the function throws an exception if the provided file does not exist.
None test_not_full_pose (self)
This method verifies that the function throws an exception if any of the poses do not define all three numbers (X, Y, and Yaw)
None test_not_numbers (self)
This method verifies that the function throws an exception if any of the poses are not composed of numbers.
None test_with_invalid_characters (self)
This method verifies that reading poses fails if any other character is used as a separator.
None test_with_whitespace (self)
This method verifies that reading poses when formatted with whitespace is successful.
Detailed Description
This class tests the read_poses function.
Definition at line 215 of file test_configuration_loader.py.
Member Function Documentation
test_empty_file()
None ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_empty_file (self)
This method verifies that the function returns an empty list if the file is empty.
Returns
None
Definition at line 220 of file test_configuration_loader.py.
    def test_empty_file(self) -> None:
        """!
        @brief This method verifies that the function returns an empty list if the file is empty.
        @return None
        """
        input_string = '\n\n'
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            result = _load_trajectory('trajectory.txt')
            self.assertEqual(len(result), 0)
References ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_empty_file().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_empty_file().
test_nonexistent_file()
None ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_nonexistent_file (self)
This method verifies that the function throws an exception if the provided file does not exist.
Normally, we mock the file open. However, in this case, we can just pass a file that doesn't actually exist and expect the error.
Returns
None
Definition at line 230 of file test_configuration_loader.py.
    def test_nonexistent_file(self) -> None:
        """!
        @brief This method verifies that the function throws an exception if the provided file does
        not exist.
        Normally, we mock the file open. However, in this case, we can just pass a file that doesn't
        actually exist and expect the error.
        @return None
        """
        self.assertRaises(FileNotFoundError, _load_trajectory,
                          'non_a_real_file.txt')
References ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_nonexistent_file().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_nonexistent_file().
test_not_full_pose()
None ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_not_full_pose (self)
This method verifies that the function throws an exception if any of the poses do not define all three numbers (X, Y, and Yaw)
Returns
None
Definition at line 243 of file test_configuration_loader.py.
    def test_not_full_pose(self) -> None:
        """!
        @brief This method verifies that the function throws an exception if any of the poses do not
        define all three numbers (X, Y, and Yaw)
        @return None
        """
        input_string = '0.0,0.0,0.0\n0.0,0.0,\n'
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(RuntimeError, _load_trajectory, 'trajectory.txt')
        input_string = '0.0,0.0\n'
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(RuntimeError, _load_trajectory, 'trajectory.txt')
References ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_not_full_pose().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_not_full_pose().
test_not_numbers()
None ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_not_numbers (self)
This method verifies that the function throws an exception if any of the poses are not composed of numbers.
Returns
None
Definition at line 256 of file test_configuration_loader.py.
    def test_not_numbers(self) -> None:
        """!
        @brief This method verifies that the function throws an exception if any of the poses are
        not composed of numbers.
        @return None
        """
        input_string = '0.0,0.0,0.0\n0.0,0.0,the\n'
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            self.assertRaises(RuntimeError, _load_trajectory, 'trajectory.txt')
References ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_not_numbers().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_not_numbers().
test_with_invalid_characters()
None ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_with_invalid_characters (self)
This method verifies that reading poses fails if any other character is used as a separator.
Returns
None
Definition at line 266 of file test_configuration_loader.py.
    def test_with_invalid_characters(self) -> None:
        """!
        @brief This method verifies that reading poses fails if any other character is used as a
        separator.
        @return None
        """
        input_string = '0.0, 0.0, 0.0\n1.0, 2.0, 3.0\n\n'
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            with self.assertRaises(RuntimeError, msg='Invalid separator characters not rejected'):
                _ = _load_trajectory('trajectory.txt')
References ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_with_invalid_characters().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_with_invalid_characters().
test_with_whitespace()
None ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_with_whitespace (self)
This method verifies that reading poses when formatted with whitespace is successful.
Returns
None
Definition at line 277 of file test_configuration_loader.py.
    def test_with_whitespace(self) -> None:
        """!
        @brief This method verifies that reading poses when formatted with whitespace is successful.
        @return None
        """
        input_string = '0.0 0.0 0.0\n1.0 2.0 3.0\n\n'
        expected_results = [[0.0, 0.0, 0.0], [1.0, 2.0, 3.0]]
        with patch(target='builtins.open', new=mock_open(read_data=input_string)):
            results = _load_trajectory('trajectory.txt')
            self.assertListEqual(list1=results, list2=expected_results,
                                 msg='Poses not successfully read from file.')
References ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_with_whitespace().
Referenced by ground_texture_sim.tests.test_configuration_loader.TestLoadTrajectory.test_with_whitespace().
The documentation for this class was generated from the following file:
ground_texture_sim/tests/test_configuration_loader.py