Ground Texture Sim: ground_texture_sim.tests.test_blender_interface.TestBlenderInterface Class Reference
ground_texture_sim.tests.test_blender_interface.TestBlenderInterface Class Reference
Tests the BlenderInterface class.
Public Member Functions
None test_camera_name_default (self)
Tests that the camera name assumes a default value if not specified.
None test_camera_name_invalid (self)
Tests an exception is raised if the provided name doesn't match the one in Blender.
None test_camera_name_property (self)
Tests that the getters and setters work.
None test_generate_image_relative_path_error (self)
Tests that the generate_image function raises an exception if the image path is not absolute.
Detailed Description
Tests the BlenderInterface class.
Definition at line 10 of file test_blender_interface.py.
Member Function Documentation
test_camera_name_default()
None ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_default (self)
Tests that the camera name assumes a default value if not specified.
Returns
None
Definition at line 15 of file test_blender_interface.py.
    def test_camera_name_default(self) -> None:
        """!
        @brief Tests that the camera name assumes a default value if not specified.
        @return None
        """
        with patch(target='bpy.data') as mock:
            mock.cameras = MagicMock()
            mock.cameras.keys = MagicMock()
            mock.cameras.keys.return_value = ['Camera']
            interface = BlenderInterface()
            self.assertEqual(interface.camera_name, 'Camera',
                             msg='Default camera name not correct.')
References ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_default().
Referenced by ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_default().
test_camera_name_invalid()
None ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_invalid (self)
Tests an exception is raised if the provided name doesn't match the one in Blender.
Returns
None
Definition at line 28 of file test_blender_interface.py.
    def test_camera_name_invalid(self) -> None:
        """!
        @brief Tests an exception is raised if the provided name doesn't match the one in Blender.
        @return None
        """
        with patch(target='bpy.data') as mock:
            mock.cameras = MagicMock()
            mock.cameras.keys = MagicMock()
            mock.cameras.keys.return_value = ['Camera']
            # Make sure the constructor raises an error.
            with self.assertRaises(NameError,
                                   msg='Constructor does not raise '
                                   'exception on invalid camera name.'):
                _ = BlenderInterface(camera_name='fake_camera')
            # Make sure the setter raises an error.
            interface = BlenderInterface()
            with self.assertRaises(NameError,
                                   msg='Setter does not raise exception on invalid camera name.'):
                interface.camera_name = 'fake_camera'
References ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_invalid().
Referenced by ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_invalid().
test_camera_name_property()
None ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_property (self)
Tests that the getters and setters work.
Returns
None
Definition at line 48 of file test_blender_interface.py.
    def test_camera_name_property(self) -> None:
        """!
        @brief Tests that the getters and setters work.
        @return None
        """
        with patch(target='bpy.data') as mock:
            mock.cameras = MagicMock()
            mock.cameras.keys = MagicMock()
            mock.cameras.keys.return_value = ['c01', 'c55']
            interface = BlenderInterface('c01')
            self.assertEqual(interface.camera_name, 'c01',
                             msg='Camera name not set on construction.')
            interface.camera_name = 'c55'
            self.assertEqual(interface.camera_name, 'c55',
                             msg='Camera name not correctly set.')
References ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_property().
Referenced by ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_camera_name_property().
test_generate_image_relative_path_error()
None ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_generate_image_relative_path_error (self)
Tests that the generate_image function raises an exception if the image path is not absolute.
Returns
None
Definition at line 64 of file test_blender_interface.py.
    def test_generate_image_relative_path_error(self) -> None:
        """!
        @brief Tests that the generate_image function raises an exception if the image path is not
        absolute.
        @return None
        """
        with patch(target='bpy.data') as mock:
            mock.cameras = MagicMock()
            mock.cameras.keys = MagicMock()
            mock.cameras.keys.return_value = ['Camera']
            with self.assertRaises(ValueError, msg='Relative path does not raise error.'):
                interface = BlenderInterface()
                interface.generate_image(
                    'relative_path/image.png', numpy.identity(4))
References ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_generate_image_relative_path_error().
Referenced by ground_texture_sim.tests.test_blender_interface.TestBlenderInterface.test_generate_image_relative_path_error().
The documentation for this class was generated from the following file:
ground_texture_sim/tests/test_blender_interface.py