name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: BUILD_TEST=ON
          context: .
          load: true
          no-cache: true
          push: false
          tags: ground-texture-sim:test
          target: build
      - name: Run Unit Tests
        run: docker run ground-texture-sim:test ctest -VV

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: BUILD_TEST=ON
          context: .
          load: true
          no-cache: true
          push: false
          tags: ground-texture-sim:test
          target: build
      - name: Run Sim and Code
        run: |
          docker run --name integration-test -d ground-texture-sim:test ign launch launch/simulate.ign gui:=false
          docker exec integration-test follow_trajectory config/trajectory.txt
          docker kill integration-test