name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: BUILD_TEST=OFF
          context: .
          load: true
          push: false
          tags: ground-texture-sim:test
          target: build
      - name: Run Unit Tests
        run: docker run ground-texture-sim:test ctest -VV

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    # The build stage has all of the code built, include gtest, so it is easy to run unit tests from there.
    - name: Build the Docker image
      run: docker build . --build-arg BUILD_TEST=ON --target build --file Dockerfile --tag ground-texture-sim:test
    - name: Run tests
      run: docker run ground-texture-sim:test ctest -VV
